# -*- coding: utf-8 -*-
"""tseries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fWCcAoVTKZg_CLxxsj1glCFWOEhA9uLG
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import files

# Upload file
uploaded = files.upload()

# Read the uploaded CSV file
df = pd.read_csv('top_1000_details.csv')

# Show first few rows
df.head()

print(df.describe())

df.columns

lc=df.sort_values(by='likeCount',ascending=False)
print(lc[['id','likeCount','favoriteCount']])

df.drop_duplicates(inplace=True)
df.rename(columns={'viewCount':'views'},inplace=True)
df.rename(columns={'likeCount':'likes'},inplace=True)
df.columns

df.dropna(inplace=True)

df.drop(columns=['favoriteCount'],inplace=True) #the columns has removed already

df.columns #no favoriteCount column is present
print(df.head(3))

top_view=df.sort_values(by='views',ascending=False).head(15)
print(top_view[['title','views','published_at']])

df['likes'] = pd.to_numeric(df['likes'], errors='coerce')
latest = df[df['likes'] > 10000000]
print(latest[['views','likes']])

plt.figure(figsize=(10,6))
sns.histplot(data=latest,color='green')
plt.title('Distribution of Likes')
plt.show()

plt.figure(figsize=(10,6))
sns.lineplot(data=latest,color='green')
plt.title('Distribution of Likes')
plt.show()

print(latest.count())

plt.figure(figsize=(10,6))
sns.heatmap(df.drop(columns=['id', 'title', 'description', 'thumbnail_url', 'published_at']).corr(),annot=True)
plt.title('Correlation Heatmap')
plt.show()

plt.figure(figsize=(10,6))
sns.pairplot(df.drop(columns=['id', 'title', 'description', 'published_at']))
plt.title('Pairplot')
plt.show()

plt.figure(figsize=(10,6))
plt.pie(latest['likes'],labels=latest['views'],autopct='%1.1f%%')
plt.title('Pie Chart of Likes')
plt.show()